name: Sample pytest workflow
on: push
jobs:
    pytest-sample:
      name: Ubuntu Base 
      runs-on: ubuntu-latest
      steps:
            - name: Checking the code
              uses: actions/checkout@v3
              with:
                   python-version: '3.10'
            - name: Installing the dependencies
              run: pip install pytest
                   pip install pytest-html
            
            - name: Performing pytest command exection
              run: pytest -v -s
            - name: Archive Test results
              uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: sample_test/reports.html
          
              
